# Generated by Django 5.1.4 on 2024-12-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='User Name')),
                ('color', models.CharField(max_length=100, verbose_name='User Preferred Color')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Game ID')),
                ('name', models.CharField(max_length=100, verbose_name='Game Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('createb_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameuser', verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Card Value')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Card in Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameuser', verbose_name='Card for User')),
            ],
        ),
    ]
