# Generated by Django 5.1.4 on 2024-12-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameUser',
            new_name='User',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('users', models.ManyToManyField(to='game.user', verbose_name='Users in Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.team', verbose_name='Game for Team'),
        ),
    ]
