# Generated by Django 5.1.4 on 2024-12-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_gameuser_user_team_game_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='createb_by',
            new_name='created_by',
        ),
    ]
