# Generated by Django 5.1.4 on 2024-12-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_createb_by_game_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_by',
        ),
        migrations.AddField(
            model_name='game',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
